services:
  debian:
    image: python:3.14-trixie
    command: /entrypoint.sh
    volumes:
      - ./binary_dump:/binary_dump:rw
      - ./debian_entrypoint.sh:/entrypoint.sh:ro
      - ./requirements.txt:/requirements.txt:ro
      - ./src:/src:ro
