services:
  linux:
    image: alpine
#    command: id
    command: sleep 6000 #/bin/ash /entrypoint.sh
    volumes:
      - ./dockerout:/dataout:rw
      - ./bash_linux.sh:/entrypoint.sh:ro
      - ./requirements.txt:/requirements.txt:ro
      - ./src:/src:ro
#    user: 1000:1000
#  --paths venv/lib/python3.14/site-packages